apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.4
          args: [ "start-dev","--http-relative-path=keycloak/auth"]
          envFrom:
            - configMapRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /keycloak/auth/realms/school # Adjusted path
              port: 8080
            initialDelaySeconds: 30  # Add delay to allow Keycloak to start up
            periodSeconds: 10  # Check every 10 seconds (adjust as needed)

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: keycloak
#spec:
#  ingressClassName: "nginx"
#  rules:
#    - host: a2c93c1880eac4359b4e649c5df01d13-2037815601.us-east-1.elb.amazonaws.com
#      http:
#        paths:
#          - path: /keycloak/
#            pathType: Prefix
#            backend:
#              service:
#                name: keycloak
#                port:
#                  number: 80