apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_HOSTNAME_ADMIN_URL: "localhost"
  KC_PROXY: "edge"
  KC_DB: "postgres"
  KC_DB_PASSWORD: "gitpass2016"
  KC_DB_URL: "jdbc:postgresql://postgres-service:5432/school"
  KC_DB_USERNAME: "postgres"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"