spring:
    application:
        name: users


    datasource:
        password: "gitpass2016"
        url: jdbc:postgresql://localhost:5432/school
        username: "postgres"
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8081

